#!/usr/bin/env zsh

! command -v git > /dev/null && echo >&2 "git is not installed, run sudo pacman -S git" && return 0

alias ga='git add'
alias gapa='git add --patch'
alias gap='git apply'

alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gbD='git branch -D'

alias gc='git commit'
alias gc!='git commit --amend'
alias gcn!='git commit --no-edit --amend'
alias gca='git commit --all'
alias gca!='git commit --all --amend'
alias gcan='git commit --all --no-edit'
alias gcan!='git commit --all --no-edit --amend'
alias gcam='git commit --all --message'
alias gcmsg='git commit --message'
alias gcb='git checkout -b'
alias gcm='git checkout master'
alias gcd='git checkout develop'
alias gco='git checkout'

alias gsw='git switch'
alias gswc='git switch --create'
alias gswd='git switch --detach'

alias gd='git diff'
alias gds='git diff --staged'

alias gpsup='git push --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)"'

alias gl='git pull'
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"

alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpf!='git push --force'

alias grh='git reset'
alias grhh='git reset --hard'
alias groh='git reset origin/$(git rev-parse --abbrev-ref HEAD) --hard'

alias grup='git remote update --prune'

alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive'

alias gst='git status --short'
alias gsb='git status --short --branch'
alias gsh='git show'
alias gsta='git stash push'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'

alias gtl='gtl(){ git tag --sort=-v:refname -n -l ${1}\* }; noglob gtl'

# vim:syntax=zsh

