#!/usr/bin/env zsh

yarn() {
    docker run --rm --interactive --tty \
        --user $(id -u):$(id -g) \
        --volume $PWD:/app \
        --workdir /app \
        --publish ${PORT:-3000}:3000 \
        node:16 yarn "$@"
}

# vim:syntax=zsh tabstop=4 shiftwidth=4 expandtab

