#!/usr/bin/env zsh

HISTFILE=$ZCACHEDIR/history
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTORY_IGNORE="(&|[ ]*|exit|l[sla]*|echo*|bg|fg|history)" # Do not add these commands to history

setopt HIST_IGNORE_ALL_DUPS # Ignore duplicated commands
setopt HIST_IGNORE_DUPS     # Ignore duplicated commands history list
setopt INC_APPEND_HISTORY   # Add commands to HISTFILE in order of execution
setopt HIST_IGNORE_SPACE    # Ignore command starting with spaces

# vim:syntax=zsh tabstop=4 shiftwidth=4 expandtab

