#!/usr/bin/env zsh

declare -A plugins
plugins=(
    zsh-syntax-highlighting ${ZDOTDIR}/deps/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    zsh-autosuggestions ${ZDOTDIR}/deps/zsh-autosuggestions/zsh-autosuggestions.zsh
)

for plugin file in ${(kv)plugins}; do
    if [[ ! -f $file ]]; then
        echo "$plugin is not installed, run \`git submodule init && git submodule update\` to dismiss this message"
    else
        source $file
    fi
done

unset plugins plugin file

# vim:syntax=zsh tabstop=4 shiftwidth=4 expandtab

