#!/bin/sh

case "$1" in
    lock) lock;;
    logout) loginctl terminate-session '';;
    suspend) lock & sleep 1; systemctl suspend;;
    reboot) systemctl reboot;;
    poweroff) systemctl poweroff;;
    *) echo "Usage: $0 {lock|logout|suspend|reboot|poweroff}" && exit 2
esac

exit 0

# vim:syntax=sh tabstop=4 shiftwidth=4 expandtab
