#!/bin/sh

[[ -z $MANPAGER ]] && notify-send --urgency critical "Environment" "Environment variable \$MANPAGER is not defined" && exit -1

MAN=$(man -k . | sort | dmenu -l 10 | awk '{ print $2 " " $1 }' | tr -d '()')

[[ -z $MAN ]] && exit

st -t Man -T Man -e man $MAN
