#!/bin/bash

resource=$HOME/.config/i3/resources/nerdfonts

# Download latest nerdfont cheatsheet and extract unicode value with description text
curl https://nerdfonts.com/ > nerdfonts-html
cat nerdfonts-html | grep "\"codepoint\"" | sed 's/.*nf-\([[:alpha:]]\+\)-\([[:alnum:]_]\+\).*\([[:xdigit:]]\{4\}\).*/\\u\3 \1 \2/' > nerdfonts-light

[[ -f $resource ]] && rm $resource

# Parse each line to get the unicode char with description to be searchable
while IFS='' read -r line  || [[ -n $line ]]; do
    char=`echo $line|cut -d' ' -f1`
    variant=`echo $line|cut -d' ' -f2`
    description=`echo $line|cut -d' ' -f3`
    echo -e $char $variant $description >> $resource
done < nerdfonts-light

# Cleanup
rm nerdfonts-html nerdfonts-light

# vim:syntax=sh tabstop=4 shiftwidth=4 expandtab

