#!/bin/bash

# Scroll up
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  xbacklight -inc 5
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  xbacklight -dec 5
fi

if [[ -z $URGENT_VALUE ]]; then
  URGENT_VALUE=10
fi

curBrightness=$(xbacklight -get)
percent=${curBrightness%.*}
printf "% 4d%%\n" $percent
printf "% 4d%%\n" $percent
printf ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

