#!/usr/bin/env zsh

if [[ $BLOCK_BUTTON -eq 1 ]]; then
    today=$(date +%e)
    span="<span bgcolor=\"$(xrdb -get dunst.color4)\">$today<\/span>"
    cal=$(cal | sed -r "s/ $today / $span /;s/ $today/ $span/;s/$today /$span /")
    notify-send "`date \"+%a %d %B\"`" "<span gravity=\"west\" color=\"white\">$cal</span>"
fi

date=$(date  '+%Y-%m-%d %H:%M')

echo $date
echo $date
echo white
echo $(xrdb -get i3blocks.background)
