#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) $TERMINAL -t "System update" -T "System update" \
		-e zsh -c "echo 'These packages will be updated' && yay -Qu|more && yay -Syu && read -sk1 \"?Update completed. Press any key to continue...\"";;
	2) notify-send "$(/usr/bin/yay -Qu)" ;;
	3) pgrep -x dunst > /dev/null && notify-send "Upgrade module" "📦: number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
esac

echo $(yay -Qu | grep -v "\[ignored\]" | wc -l)
echo $(yay -Qu | grep -v "\[ignored\]" | wc -l)
echo $(xrdb -get i3blocks.fadeColor)
echo $(xrdb -get i3blocks.color3)
