#!/usr/bin/env zsh
upower_path=`upower -e|awk "/${mac//:/_}/"' {print $0}'`
percentage=`upower -i $upower_path|awk '/percentage/ { print $2 }'|tr -d %`

foreground=$(xrdb -get i3blocks.background)
if [[ $percentage -lt 20 ]]; then
  foreground=$(xrdb -get i3blocks.color1);
elif [[ $percentage -lt 40 ]]; then
  foreground=$(xrdb -get i3blocks.color5);
elif [[ $percentage -lt 60 ]]; then
  foreground="#D08770";
elif [[ $percentage -lt 85 ]]; then
  foreground=$(xrdb -get i3blocks.color4);
fi

echo $percentage%
echo $percentage%
echo $foreground
echo $(xrdb -get i3blocks.color3)

# vim:syntax=zsh tabstop=4 shiftwidth=4 expandtab
