#!/usr/bin/env zsh

alias ls='ls --color=always'
alias ll='ls -lHh'

alias tree='tree -C'

alias lsblk='lsblk -o NAME,LABEL,SIZE,FSUSED,FSUSE%,FSAVAIL,MOUNTPOINT,FSTYPE'

alias _='sudo'

# vim:syntax=zsh
