#!/usr/bin/env zsh

[[ ! -x /usr/bin/docker-compose ]] && echo "docker-compose is not installed, run sudo pacman -S docker-compose" && return 0

alias dc='sudo docker-compose'
alias dce='sudo docker-compose exec'
alias dcl='sudo docker-compose logs -f'
alias docker="sudo docker"

# vim:syntax=zsh

