#!/usr/bin/env zsh

! command -v docker-compose > /dev/null && echo >&2 "docker-compose is not installed, run sudo pacman -S docker-compose" && return 0

alias dc=docker-compose
alias dce='docker-compose exec'
alias dcl='docker-compose logs -f'

# vim:syntax=zsh

