#!/usr/bin/env zsh

! command -v docker > /dev/null && echo >&2 "docker and/or docker compose are not installed, run sudo pacman -S docker docker-compose" && return 0

alias dc=docker compose
alias dce='docker compose exec'
alias dcl='docker compose logs -f'
alias dcrm='docker compose rm'

alias dil='docker images list'
alias dirm='docker image rm'
alias dnl='docker network list'
alias dnrm='docker network rm'
alias dvl='docker volume list'
alias dvrm='docker volume rm'
alias drm='docker rm'
alias dps='docker ps'
alias dpsa='docker ps --all'

# vim:syntax=zsh

